id: sync_bom
namespace: scheduler

triggers:
  - id: hourly
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 * * * *"

tasks:
  - id: call_sync_bom
    type: io.kestra.plugin.core.http.Request
    uri: "http://laser-tender:3126/api/sync-bom"
    method: POST
    headers:
      Authorization: "Bearer {{ secret('KESTRA_EXTERNAL_API_KEY') }}"
      x-api-key: "{{ secret('KESTRA_EXTERNAL_API_KEY') }}"
